// 把 App 自有命令纳入 ACL——Tauri v2 默认允许任意窗口调用所有 invoke_handler 命令，
// 列入 AppManifest::commands 后这些命令改为「必须在 capability 显式 allow」，
// 从而能把不可信的插件窗口（itplugin 远程源）限制为只能调 plugin_* 白名单。
// 每个命令会生成 allow-<kebab-name> / deny-<kebab-name> 权限，在 capabilities/*.json 里引用。
// 需 'static，故用 const（AppManifest::commands 要求 &'static [&'static str]）。
const COMMANDS: &[&str] = &[
        // 主程序命令（仅 main/admin 授予）
        "search",
        "execute",
        "load_icons",
        "home_data",
        "toggle_pin",
        "get_settings",
        "save_settings",
        "pick_image",
        "pick_app",
        "read_image",
        "read_avatar",
        "get_profile",
        "set_nickname",
        "set_avatar",
        "account_state",
        "account_login",
        "set_data_sync",
        "sync_now",
        "logout_account",
        "delete_account",
        "pick_launch_files",
        "pick_launch_folder",
        "add_launch_items",
        "remove_launch_items",
        "run_launch_item",
        "build_launch_item",
        "open_admin_window",
        "close_admin_window",
        "set_settings_persist",
        "check_update",
        "get_app_version",
        "open_release_page",
        "download_update",
        "launch_installer_and_quit",
        "open_plugin_window",
        "rescan_plugins",
        "list_plugins",
        "set_plugin_enabled",
        "set_plugin_permission",
        "delete_plugin",
        // 插件命令（仅 plugin 窗口授予）
        "plugin_take_enter",
        "plugin_hide",
        "plugin_exit",
        "plugin_set_height",
        "plugin_copy_text",
        "plugin_read_text",
        "plugin_read_image",
        "plugin_write_image",
        "plugin_save_image",
        "plugin_read_file",
        "plugin_write_file",
        "plugin_remove_file",
        "plugin_open_external",
        "plugin_open_path",
        "plugin_notify",
        "plugin_run_command",
        "plugin_fetch",
        "plugin_db_get",
        "plugin_db_set",
        "plugin_db_remove",
        "plugin_db_keys",
        "plugin_list_displays",
        "plugin_capture_full",
        "plugin_capture_region",
        // 由截图覆盖层窗口（capture-overlay）调用，不授予插件窗口
        "capture_region_report",
        "capture_overlay_ready",
        "plugin_register_hotkey",
        "plugin_unregister_hotkey",
        "plugin_create_pin",
        // 由贴图窗口（pin-*）调用，作用于自身
        "pin_resize",
        "pin_move",
        "pin_close",
        "plugin_ocr",
        "plugin_start_audio_record",
        "plugin_stop_audio_record",
        "plugin_start_gif_record",
        "plugin_stop_gif_record",
        "plugin_account_state",
        "plugin_data_get",
        "plugin_data_set",
        "plugin_data_remove",
        "plugin_data_keys",
        "plugin_data_sync",
        // 插件详情页：README 读取 + schema 驱动设置（管理中心按 name 显式 + 插件运行时只读）
        "plugin_readme",
        "plugin_settings_schema",
        "plugin_settings_values",
        "plugin_settings_set",
        "plugin_settings_reset",
        "plugin_get_settings",
        "plugin_get_setting",
];

fn main() {
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS));
    tauri_build::try_build(attributes).expect("tauri build 失败");
}
